name: Build and deploy Python app to docker Hub

env:
  PYTHON_VERSION: '3.8'              # set this to the Python version to use
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_DATABASE: portfolio_db
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Set up Python version
      #   uses: actions/setup-python@v3.0.0
      #   with:
      #     python-version: ${{ env.PYTHON_VERSION }}
      #     cache: 'pip'

      # - name: Create and start virtual environment
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate

      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      # - name: Upload artifact for deployment jobs
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: python-app
      #     path: |
      #       .
      #       !venv/
       
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: kuro08/portfolio
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  #deploy:
  #  permissions:
  #    contents: none
  #  runs-on: ubuntu-latest
  #  needs: build
  #  environment:
  #    name: 'Development'
  #    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
  #  steps:
  #    - name: Download artifact from build job
  #      uses: actions/download-artifact@v3
  #      with:
  #        name: python-app
  #        path: .
#
  #    - name: 'Deploy to Azure Web App'
  #      id: deploy-to-webapp
  #      uses: azure/webapps-deploy@v2
  #      with:
  #        app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#
